repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version available
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: pytest  # Adjust this line if you're using a different command to run tests
        language: system
        pass_filenames: false
